const hotel = [
    {
        title : "The Jade Hotel",
        image : "jade.jpg",
        location: "Hanoi",
        address: "jade.html",
        trending: "no",
        rating: 4.5,
    },
    {
        title : "La Siesta Mamay ",
        image : "mamay.jpg",
        location: "Hanoi",
        address: "mamay.html",
        trending: "no",
        rating: 4,
    },
    {
        title : "La Siesta Resort",
        image : "resort.jpg",
        location: "Hoi An",
        address: "resort.html",
        trending: "yes",
        rating: 4,
    },
    {
        title : "Allegro Luxury",
        image : "allegro.jpg",
        location: "Nha Trang",
        address: "allegro.html",
        trending: "yes",
        rating: 4,
    },
    {
        title : "Premier Village",
        image : "premier.jpg",
        location: "Da Nang",
        address: "premier.html",
        trending: "yes",
        rating: 5,
    },
    {
        title : "Solaria Hotel",
        image : "solaria.jpg",
        location: "Ho Chi Minh City",
        address: "solaria.html",
        trending: "yes",
        rating: 4,
    },
    {
        title : "Anio Boutique",
        image : "anio.jpg",
        location: "Hue",
        address: "anio.html",
        trending: "yes",
        rating: 5,
    },
    {
        title : "Grand Mercure",
        image : "mercure.jpg",
        location: "Hanoi",
        address: "mercure.html",
        trending: "no",
        rating: 5,
    },
    {
        title : "Hôtel de la Coupole",
        image : "coupole.jpg",
        location: "Phu Quoc",
        address: "coupole.html",
        trending: "no",
        rating: 4.5,
    },    
    {
        title : "La Siesta Mamay ",
        image : "mamay.jpg",
        location: "Hanoi",
        address: "mamay.html",
        trending: "yes",
        rating: 4,
    },
    {
        title : "La Siesta Resort",
        image : "resort.jpg",
        location: "Hoi An",
        address: "resort.html",
        trending: "yes",
        rating: 5,
    },
    {
        title : "Allegro Luxury",
        image : "allegro.jpg",
        location: "Nha Trang",
        address: "allegro.html",
        trending: "yes",
        rating: 4.5,
    },
    {
        title : "Premier Village",
        image : "premier.jpg",
        location: "Da Nang",
        address: "premier.html",
        trending: "yes",
        rating: 4.5,
    },
    {
        title : "Solaria Hotel",
        image : "solaria.jpg",
        location: "Ho Chi Minh City",
        address: "solaria.html",
        trending: "yes",
        rating: 5,
    },
    {
        title : "Anio Boutique",
        image : "anio.jpg",
        location: "Hue",
        address: "anio.html",
        trending: "yes",
        rating: 5,
    },
    {
        title : "Grand Mercure",
        image : "mercure.jpg",
        location: "Hanoi",
        address: "mercure.html",
        trending: "yes",
        rating: 4,
    },

]



localStorage.setItem("hotel", JSON.stringify(hotel));